name: Deploy PHP App

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repository code

      - name: Set up PHP
        uses: shivammathur/setup-php@v2  # Set up PHP environment
        with:
          php-version: '8.0'  # Specify PHP version
          tools: composer

      - name: Install dependencies
        run: composer install --working-dir=./edmissions-co/login-signup-php/  # Install dependencies in the app subfolder

      # - name: Run tests
        # run: php app/vendor/bin/phpunit --configuration app/phpunit.xml  # Run tests from the app subfolder

 # Step to install lftp
      - name: Install lftp
        run: sudo apt-get install -y lftp  # Install lftp

      - name: Deploy to Server
        env:
          FTP_USERNAME: ${{ secrets.DEPLOY_USER }}  # Set up FTP/SSH details in GitHub secrets
          FTP_PASSWORD: ${{ secrets.DEPLOY_KEY }}
        run: |
          lftp -e "
          mirror --reverse --delete --verbose ./edmissions-co/login-signup-php/ ./edmissions-co/login-signup-php/;
          bye
          " -u $DEPLOY_USER,$DEPLOY_KEY ftp://your-server.com
